name: Build and publish release

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish (Windows)
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate release notes
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Generating release notes for version $VERSION"
          node generate-release.js $VERSION

      - name: Build and publish installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release

      - name: Create GitHub Release
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          RELEASE_NOTES_FILE="release-v$VERSION.md"

          if [ -f "$RELEASE_NOTES_FILE" ]; then
            echo "Creating GitHub release with generated notes..."
            gh release create ${{ github.ref_name }} \
              --title "Local Image Browser for InvokeAI ${{ github.ref_name }}" \
              --notes-file "$RELEASE_NOTES_FILE" \
              --generate-notes
          else
            echo "Release notes file not found, creating basic release..."
            gh release create ${{ github.ref_name }} \
              --title "Local Image Browser for InvokeAI ${{ github.ref_name }}" \
              --generate-notes
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List dist-electron contents (for debug)
        if: always()
        run: |
          echo "== dist-electron files =="
          dir dist-electron

  build-and-publish-mac:
    name: Build and publish (macOS)
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and publish DMG
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release

      - name: List dist-electron contents (for debug)
        if: always()
        run: |
          echo "== dist-electron files =="
          ls -lh dist-electron

  build-and-publish-linux:
    name: Build and publish (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install system dependencies for AppImage
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2

      - name: Build and publish AppImage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release

      - name: List dist-electron contents (for debug)
        if: always()
        run: |
          echo "== dist-electron files =="
          ls -lh dist-electron
