name: Build and publish macOS

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish-mac:
    name: Build and publish (macOS)
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and publish installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed, checking dist folder..."
          ls -la dist/
          echo "Starting electron-builder..."
          npx electron-builder --mac --publish=never

      - name: Upload macOS assets to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Uploading macOS assets for version v$VERSION"

          # Upload all macOS files (DMG files)
          if [ -d "dist-electron" ]; then
            for file in dist-electron/*; do
              if [ -f "$file" ] && [[ "$file" == *.dmg ]]; then
                echo "Uploading $file to release v$VERSION..."
                gh release upload v$VERSION "$file" --clobber
              fi
            done
          fi

      - name: List dist-electron contents (for debug)
        if: always()
        run: |
          echo "== Build artifacts =="
          if [ -d "dist-electron" ]; then
            echo "dist-electron contents:"
            ls -lh dist-electron/
          else
            echo "dist-electron directory not found!"
          fi